" Search and highlight while typing while ignoring case when only lower case used
set ignorecase      " ignore case in search patterns
set smartcase       " use case-sensisitve search if pattern contains upper case
set incsearch       " incremental aearch
set hlsearch        " highlight all search pattern matches

" Use spaces for tabs
set tabstop=4       " how wide a Tab character is defnied
set softtabstop=4   " how far cursor moves while typing Tab
set shiftwidth=4    " Number of spaces to use for each step of (auto)indent
set expandtab       " convert tab characters to spaces

let g:tmux_navigator_no_wrap = 1


" Normally this if-block is not needed, because `:set nocp` is done
" automatically when .vimrc is found. However, this might be useful
" when you execute `vim -u .vimrc` from the command line.
if &compatible
  " `:set nocp` has many side effects. Therefore this should be done
  " only when 'compatible' is set.
  set nocompatible
endif


function! PackInit() abort
  packadd minpac

  call minpac#init()

  " Additional plugins here.
  call minpac#add('vimwiki/vimwiki')
endfunction

" Plugin settings here.

" Define user commands for updating/cleaning the plugins.
" Each of them calls PackInit() to load minpac and register
" the information of plugins, then performs the task.
command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus packadd minpac | call minpac#status()
