# Keep long command history
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt APPEND_HISTORY

setopt autocd extendedglob nomatch
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/alex/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
